### ISSUE TITLE
my truck has snow on it

### ISSUE THREAD

**Issue by AstridWasHereLOL** [WaviestBalloon/ApplejuiceCLI#22]
![2024-02-09_20-28](https://github.com/WaviestBalloon/ApplejuiceCLI/assets/51385987/a7ab1af1-e1c6-49fe-8cde-cfc8ea249248)
i live in arizona i dont know how to deal with this please help

also framerate and performance very najs, gooj dob

**Comment by WaviestBalloon** [comment]
:3
