### ISSUE TITLE
BloxstrapRPC Protocol adoption

### ISSUE THREAD

**Issue by WaviestBalloon** [WaviestBalloon/ApplejuiceCLI#3]
I have been in cahoots with pizzaboxer and we both agreed that integrating the BloxstrapRPC protocol would be cool. :)
~~Unfortunately as of now, we have no way of getting the current log files for the running instance of Roblox as we haven't yet figured out the issue with Proton prefixes and library issues.~~

**Comment by pizzaboxer** [comment]
youve been in what now

**Comment by WaviestBalloon** [comment]
> youve been in what now

👩‍💻

**Comment by WaviestBalloon** [comment]
The reason this feature is taking a while is because I'm trying to find the best way to get live updates from a log file, after that I'll be cleaning up stdout and code formatting.

**Comment by pizzaboxer** [comment]
![image](https://github.com/WaviestBalloon/ApplejuiceCLI/assets/41478239/fe0a9f7d-19f2-4f47-a86d-edf76e05a183)

**Comment by apprehensions** [comment]
managed to do it in vinegar by overbothering pizzaboxer: 
https://github.com/vinegarhq/vinegar/commit/3369404bc7ff37cbc90d646d27e65736b1022bef

**Comment by WaviestBalloon** [comment]
After some more research I've found a solution to tailing files, partial BloxstrapRPC integration is implemented although I've now encountered multiple issues with the Discord Rich Presence library I'm using and seeking a replacement.

It may seem like I'll have to create my own RPC library but that will definitely extend the time it will take to push the newest changes to the repository.
And I forget that college exists. :c

**Comment by WaviestBalloon** [comment]
Protocol implementation has been added as the 100th commit :3
Commit: https://github.com/WaviestBalloon/ApplejuiceCLI/commit/22d4aba8ec8486a8844fb714b469ffda685b96a1

Will close this Issue once I do more testing!

**Comment by WaviestBalloon** [comment]
Pushed a bug fix (https://github.com/WaviestBalloon/ApplejuiceCLI/commit/1ac05687998d6d39721082e5b4354d4aecf9f64c) to resolve rich presences stuck on "elapsed"
As of now, there are only two or so bugs that are not serious in any way, closing as complete now
